# Starship Prompt Configuration

# Custom format of the prompt
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$python\
$character"""

# Username Module
[username]
format = "[$user]($style)@"
style_user = "bold green"

# Hostname Module
[hostname]
format = "[$hostname]($style) "  # Space added at the end
style = "bold yellow"

# Directory Module
[directory]
style = "blue"
format = "[$path]($style) "  # Space added at the end

# Character Module
[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

# Git Branch Module
[git_branch]
format = "on [ $branch]($style) "

# Git Status Module
[git_status]
style = "cyan"
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "!${count}"
untracked = "?${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

# Git State Module
[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

# Command Duration Module
[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

# Python Module
[python]
format = "[$virtualenv]($style) "
style = "bright-black"

