# Starship Prompt Configuration

# General Settings
add_newline = false  # Prevents adding a new line at the start of the prompt

# Main Prompt Format
# Defines the layout and modules for the left-aligned part of the prompt
format = """
$env_var\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$character"""

# Right Prompt Format
# Defines modules to be displayed on the right side of the prompt
right_format = "$time $os"

# MODULE: Time
# DESCRIPTION: Shows the current time
[time]
disabled = false
style = "bold yellow"
format = "[󰥔 $time]($style)"

# MODULE: Username
# DESCRIPTION: Displays the current user's username
[username]
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style)@"

# MODULE: Hostname
# DESCRIPTION: Shows the hostname of the machine
[hostname]
format = "[$hostname]($style) " 
style = "bold yellow"

# MODULE: Directory
# DESCRIPTION: Displays the current working directory
[directory]
read_only = " 󰌾"
style = "blue"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_symbol = ".../"

# MODULE: Git Branch
# DESCRIPTION: Shows the current Git branch
[git_branch]
symbol = ""
format = "on [$symbol $branch]($style) "

# MODULE: Git Commit
# DESCRIPTION: Displays the current commit hash
[git_commit]
commit_hash_length = 4
style = "bold green"
format = '[\($hash\)]($style)'

# MODULE: Git Metrics
# DESCRIPTION: Displays added and deleted lines in the current Git repository
[git_metrics]
only_nonzero_diffs = true
disabled = false
added_style = "bold green"
deleted_style = "bold red"
format = '[+$added]($added_style)[-$deleted]($deleted_style) '

# MODULE: Git Status
# DESCRIPTION: Indicates changes to the working directory
[git_status]
style = "cyan"
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "!${count}"
untracked = "?${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

# MODULE: Git State
# DESCRIPTION: Displays the state of the Git repo (e.g., REBASING)
[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
merge = '[ MERGING](bold red)'
style = "bright-black"

# MODULE: Command Duration
# DESCRIPTION: Shows how long the last command took to execute
[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

# MODULE: OS
# DESCRIPTION: Displays the operating system symbol
[os]
style = "bold blue"
format = "on [$symbol]($style)"
disabled = false

# OS Symbols
# Custom symbols for different OS types
[os.symbols]
Arch = ""
Ubuntu = '󰕈'
